spring.datasource.url=jdbc:mysql://localhost:3306/productivity_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=M@nifest111777
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forțează Hibernate să construiască fizic tabelele în MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ignoră complet proprietățile jakarta.persistence.schema-generation pentru acest pas